#!/bin/bash

if [ `whoami` != root ]; then
    echo Please run this script as root or using sudo
    exit
fi

# Wait for docker
chmod 777 "/var/run/docker.sock"
docker_lock=/var/run/docker.sock
while [ ! -e $docker_lock ] ; do
  inotifywait -t 2 -e create $(dirname $docker_lock)
done

### CONSTAINTS ###

HOST=$(hostname)
IMAGE="development"
CONTAINER="$IMAGE"_container

### Docker run ###
run() {
  # shared Volumes
  if [ ! -d /docker ]; then
    mkdir -p /docker
  fi

  volumes="-v /docker:/docker"

  # ports (...)
  ports=""

  docker stop $CONTAINER > /dev/null 2>&1
  docker rm $CONTAINER > /dev/null 2>&1  
  PID=$(docker run -d -t -h $HOST $volumes -p 2222:22 $ports --name $CONTAINER $IMAGE "/usr/bin/supervisord")
}

### Terminal operations ###
while getopts "rdc:bseih" opt; do
  case $opt in
    r)
      echo "Run: $IMAGE"
      run
      ;;
    d)
      echo "Delete: $IMAGE"
      docker rmi $IMAGE
      ;;    
    c)
      echo "Commit: $CONTAINER to $IMAGE"
      docker stop $CONTAINER > /dev/null 2>&1
      docker commit -m "$OPTARG" $CONTAINER $IMAGE 
      ;;
    b)
      echo "Build: $IMAGE"
      docker build --quiet=false --no-cache=false --rm=false --tag "$IMAGE" .
      ;;
    s)
      echo "Stop: $CONTAINER"
      docker stop $CONTAINER > /dev/null 2>&1
      ;;
    e)
      echo "Export: $CONTAINER"
      docker stop $CONTAINER > /dev/null 2>&1
      docker export $CONTAINER | gzip -c > $CONTAINER.tgz
      ;;
    i)
      echo "Import: $IMAGE"
      docker stop $CONTAINER > /dev/null 2>&1
      docker rm $CONTAINER > /dev/null 2>&1
      docker rmi $IMAGE > /dev/null 2>&1
      gzip -dc "$CONTAINER".tgz | docker import - $IMAGE      
      ;;
    h)   
      echo -e "Usage: option(s)
Options:
  -(r)un
  -(d)elete
  -(c)ommit message
  -(b)uild 
  -(s)top 
  -(i)mport 
  -(e)xport
  -(h)elp"
    ;;
  esac
done

exit