# Use/Setup: tmuxinator
# ~/.tmuxinator/Development.yml

name: Development
root: ~/Development
pre:
#  - sudo <command>

windows:
  - editor:
      layout: main-horizontal
      layout: 3a6f,178x50,0,0[178x40,0,0,0,178x9,0,41,6]
      panes:
        - vim
        - #default
  - mono:
      layout: main-horizontal
      panes:
        - mono
        - mono --runtime=v4.0 lib/NuGet.exe restore <name>.sln
  - mongo:
      layout: main-horzontal
      panes:
        - mongo
        - mongostat
  - redis:
      layout: main-horizontal
      panes:
        - redis-cli
#  - ssh:
#      layout: even-vertical
#      panes:
#        - ssh <user@host>
#        - ssh <user@host>
#        - ssh <user@host>

